OPENAI_EMBEDDING_DIM=3072
DEFAULT_EMBEDDING_DIM = OPENAI_EMBEDDING_DIM
DEFAULT_CHUNK_SIZE= 500
DEFAULT_CHUNK_OVERLAP = DEFAULT_CHUNK_SIZE * 0.1

MILVUS_METRIC_TYPE='L2'
MILVUS_INDEX_TYPE='IVF_FLAT'
MILVUS_NLIST=1024
MILVUS_NPROBE=32
MILVUS_DIM=DEFAULT_EMBEDDING_DIM
MILVUS_TOP_K=10