"""change nullability

Revision ID: 6c372a2aaf6b
Revises: 126a6544371c
Create Date: 2024-12-11 23:02:15.069668

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6c372a2aaf6b'
down_revision: Union[str, None] = '126a6544371c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('naver_article_contents', 'article_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('naver_article_contents', 'ticker',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('naver_article_contents', 'ticker',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('naver_article_contents', 'article_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
